openapi: 3.0.0
info:
  title: Airports API
  description: |
    Get all your airport data [here](https://raw.githubusercontent.com/WhiteHatLearningProducts/airports/master/airportsData.json) 
  version: 1.0.0
  licence: MIT
servers:
  - url: http://localhost:3000/
  - url: https://api.whitehatcoaches.org.uk/
    description: this is the production baseURL
